### PR TITLE
Unlock altis mission for non DLC owners.

### PR DESCRIPTION
**Pull request by Alablm**

### CODE REVIEW

**Comment by SavageGameDesign** [comment]
Task linked: [CU-2na3x2e Unlock altis mission for non DLC owners.](https://app.clickup.com/t/2na3x2e)

**Comment by veteran29** [comment]
This does not remove DLC check from the mission, this array controls showing of "ads" of DLCs used in mission, DLC locking of the mission is done via `appId`: https://github.com/Savage-Game-Design/Mike-Force/blob/e13d27c6e2850c392c258d7710c9994dff7f0f23/maps/altis/mission.sqm#L325

**Comment by Spoffy** [comment]
Thanks for pointing that out @veteran29! Is this something set automatically by the engine do you know? Not sure if the fix is making the build script strip it out.

**Comment by veteran29** [comment]
App ID is set manually in the mission attributes IIRC.

**Comment by veteran29** [comment]
image

**Pull request merged**
