### PR TITLE
Fixup: Typo in stamina parameter lookup

### PR DESCRIPTION
**Pull request by IceEagle132**
Fixes broken param for stamina as it looks like someone made a typo.

### CODE REVIEW

**Review by dijksterhuis — APPROVED** [review]
yep deffo a typo.

**Review by dijksterhuis — CHANGES_REQUESTED** [review]
Would you be able to amend the commit message? 

Would ideally be something like this for the title: `Fixup: Typo in stamina parameter lookup`

At the moment it's the GitHub default "Updated: some_file_name.sqf" commit title with the actual description of the changes in the body of the commit message. 

for reference so you can see what i mean, your commit looks like this

image

whereas one of Spoffy's previous commits looks like this.

image

I know this is a bit nitpicky, and it's not critical to do, but it help future people to know what the change was at first glance without having to click on a bunch of GitHub website buttons.

**Comment by dijksterhuis** [comment]
linking back to the issue https://github.com/Savage-Game-Design/Mike-Force/issues/173

**Comment by IceEagle132** [comment]
> Fixup: Typo in stamina parameter lookup

That's very nitpicky as you can merge my fix or fix it your self or leave it broken.

**Comment by dijksterhuis** [comment]
> That's very nitpicky as you can merge my fix or fix it your self or leave it broken.

Heya @IceEagle132 -- if I squash merge this as is (or push my own PR) it'll cause a conflict on your fork's `development` branch. [0]

Let me know if you're fine dealing with that (or not bothered) then I'll squash merge as is. You're more than welcome to force push an amended commit as discussed prior.

---

[0]: best practice is to create a new feature branch from your fork's default branch to avoid these sorts of issues. GitHub calls these 'topic branches' in their [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by IceEagle132** [comment]
Never had to amend so not sure if I did it right.

**Comment by dijksterhuis** [comment]
Aye that looks like it'll be fine. thanks!

**Review by dijksterhuis — APPROVED** [review]
LGTM! :tada:

**Comment by dijksterhuis** [comment]
Tested, all working. Merging! 🎉

**Pull request merged**
